import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/lib/auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <nav
            style={{
              display: "flex",
              alignItems: "center",
              gap: "1.5rem",
              padding: "1rem 2rem",
              borderBottom: "1px solid #e5e7eb",
              background: "#fff",
              position: "relative",
              zIndex: 10,
            }}
          >
            <span style={{ fontWeight: 600, fontSize: "1.1rem", marginRight: "2rem" }}>
              MyApp
            </span>
            <Link href="/" style={{ textDecoration: "none", color: "#222" }}>
              Home
            </Link>
            <Link href="/courses" style={{ textDecoration: "none", color: "#222" }}>
              Courses
            </Link>
            <Link href="/enrollment" style={{ textDecoration: "none", color: "#222" }}>
              Enrollment
            </Link>
            <Link href="/staff/dashboard" style={{ textDecoration: "none", color: "#222" }}>
              Staff Dashboard
            </Link>
          </nav>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
